<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>WhichCOM.Core</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\usb-serial-chips.json" LogicalName="WhichCOM.Core.Data.usb-serial-chips.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WhichCOM.Core.Tests" />
  </ItemGroup>

</Project>
